source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

#  ruby '2.7.0'
# ruby '2.7.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.1.0'
# Use postgresql as the database for Active Record
gem "pg", "~> 1.2.3"
# Use Puma as the app server
gem 'puma', '~> 5.0'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'

# Use Active Model has_secure_password
gem 'bcrypt', '~> 3.1.7'

#Json Web Token for authentification
gem 'jwt'

# Socket
gem 'actioncable', '~> 6.1.0'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Rails hash to json
gem 'active_model_serializers'

#easier library to handle than the included one
gem 'httparty'

# Two Factor Authentication (TFA) made simple
gem 'active_model_otp'

#The Ruby One Time Password Library
gem 'rotp'

#easy way to create service
gem 'simple_command'

# Reduces bunboot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

gem 'rb-readline'

# Use to calculate elo rating in ladder tournament
gem 'elo', '~> 0.1.0'

# To automatically call functions on a given time
gem 'delayed_job_active_record'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '~> 4.0.1'
  gem 'factory_bot_rails'
end

group :development do
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]


